//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Love_Transcript_Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Love_Transcript_Studio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage _3stars {
            get {
                object obj = ResourceManager.GetObject("3stars", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage _new {
            get {
                object obj = ResourceManager.GetObject("new", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage actions_add {
            get {
                object obj = ResourceManager.GetObject("actions_add", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage actions_trash {
            get {
                object obj = ResourceManager.GetObject("actions_trash", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add_32x32 {
            get {
                object obj = ResourceManager.GetObject("add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage applychanges {
            get {
                object obj = ResourceManager.GetObject("applychanges", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap audiocontent_32x32 {
            get {
                object obj = ResourceManager.GetObject("audiocontent_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap audiocontent_32x321 {
            get {
                object obj = ResourceManager.GetObject("audiocontent_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage charttype_bubble3d {
            get {
                object obj = ResourceManager.GetObject("charttype_bubble3d", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap clear_16x16 {
            get {
                object obj = ResourceManager.GetObject("clear_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage clearall {
            get {
                object obj = ResourceManager.GetObject("clearall", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage deletedatasource {
            get {
                object obj = ResourceManager.GetObject("deletedatasource", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage insertgroupheader {
            get {
                object obj = ResourceManager.GetObject("insertgroupheader", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 DevExpress.Utils.Svg.SvgImage 类型的本地化资源。
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage productspecificationssummary {
            get {
                object obj = ResourceManager.GetObject("productspecificationssummary", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap trash_32x32 {
            get {
                object obj = ResourceManager.GetObject("trash_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
